[
    {
        "id": "69237e24-ab59-49d0-aeae-4d52b5211878",
        "name": "localizacao_imovel",
        "status": "Pronto",
        "created_at": "2025-06-19T04:29:42.428921",
        "updated_at": "2025-06-19T04:29:53.622233",
        "project_path": "C:\\ktr_migrator\\ktr_platform\\flows\\69237e24-ab59-49d0-aeae-4d52b5211878",
        "last_run_at": "2025-06-19T04:29:53.622233",
        "execution_status": "Falha",
        "execution_logs": [
            "[2025-06-19T04:29:52.592820] üöÄ Iniciando execu√ß√£o do fluxo...",
            "[2025-06-19T04:29:52.596923] üìÅ Executando: localizacao_imovel_pipeline.py",
            "[2025-06-19T04:29:53.482079] [ERRO] \u001b[32m2025-06-19 04:29:53.481\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36msetup_logging\u001b[0m:\u001b[36m52\u001b[0m - \u001b[1müöÄ Iniciando pipeline: localizacao_imovel\u001b[0m",
            "[2025-06-19T04:29:53.531974] [ERRO] \u001b[32m2025-06-19 04:29:53.531\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36msetup_connections\u001b[0m:\u001b[36m59\u001b[0m - \u001b[1müì° Conex√£o configurada: local (POSTGRESQL)\u001b[0m",
            "[2025-06-19T04:29:53.532974] [ERRO] \u001b[32m2025-06-19 04:29:53.531\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36msetup_connections\u001b[0m:\u001b[36m63\u001b[0m - \u001b[1müì° Conex√£o configurada: PRODUCAO (POSTGRESQL)\u001b[0m",
            "[2025-06-19T04:29:53.534478] [ERRO] \u001b[32m2025-06-19 04:29:53.531\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36mrun_pipeline\u001b[0m:\u001b[36m212\u001b[0m - \u001b[1müéØ Executando pipeline localizacao_imovel\u001b[0m",
            "[2025-06-19T04:29:53.535483] [ERRO] \u001b[32m2025-06-19 04:29:53.531\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36mextract_data\u001b[0m:\u001b[36m69\u001b[0m - \u001b[1müîÑ Iniciando extra√ß√£o de dados...\u001b[0m",
            "[2025-06-19T04:29:53.543204] [ERRO] \u001b[32m2025-06-19 04:29:53.543\u001b[0m | \u001b[31m\u001b[1mERROR   \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36mextract_data\u001b[0m:\u001b[36m95\u001b[0m - \u001b[31m\u001b[1m‚ùå Erro na extra√ß√£o: [Errno 22] Invalid argument: 'C:\\x08iserver-ce\\\\ktr\\\\Geo«ì104_Localizacao_imovel_CGDAI_Marco_25.xlsx'\u001b[0m",
            "[2025-06-19T04:29:53.544709] ‚ùå Pipeline falhou: [Errno 22] Invalid argument: 'C:\\x08iserver-ce\\\\ktr\\\\Geo«ì104_Localizacao_imovel_CGDAI_Marco_25.xlsx'",
            "[2025-06-19T04:29:53.546169] [ERRO] \u001b[32m2025-06-19 04:29:53.543\u001b[0m | \u001b[31m\u001b[1mERROR   \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36mrun_pipeline\u001b[0m:\u001b[36m254\u001b[0m - \u001b[31m\u001b[1müí• Pipeline falhou: {'records_processed': 0, 'execution_time': 0, 'errors': 1, 'status': 'failed', 'error': \"[Errno 22] Invalid argument: 'C:\\\\x08iserver-ce\\\\\\\\ktr\\\\\\\\Geo«ì104_Localizacao_imovel_CGDAI_Marco_25.xlsx'\", 'total_execution_time': 0.01123, 'end_time': '2025-06-19T04:29:53.543204'}\u001b[0m",
            "[2025-06-19T04:29:53.550179] [ERRO] \u001b[32m2025-06-19 04:29:53.544\u001b[0m | \u001b[34m\u001b[1mDEBUG   \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36mrun_pipeline\u001b[0m:\u001b[36m261\u001b[0m - \u001b[34m\u001b[1müîå Conex√£o fechada: local\u001b[0m",
            "[2025-06-19T04:29:53.551194] [ERRO] \u001b[32m2025-06-19 04:29:53.544\u001b[0m | \u001b[34m\u001b[1mDEBUG   \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36mrun_pipeline\u001b[0m:\u001b[36m261\u001b[0m - \u001b[34m\u001b[1müîå Conex√£o fechada: PRODUCAO\u001b[0m",
            "[2025-06-19T04:29:53.618225] üí• Erro detectado, interrompendo execu√ß√£o...",
            "[2025-06-19T04:29:53.623232] ‚ùå Execu√ß√£o falhou com c√≥digo None"
        ],
        "execution_start_time": "2025-06-19T04:29:52.520562",
        "execution_end_time": "2025-06-19T04:29:53.622233",
        "execution_duration": 1.101671,
        "error_message": "[EXTRA√á√ÉO] \u001b[32m2025-06-19 04:29:53.543\u001b[0m | \u001b[31m\u001b[1mERROR   \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36mextract_data\u001b[0m:\u001b[36m95\u001b[0m - \u001b[31m\u001b[1m‚ùå Erro na extra√ß√£o: [Errno 22] Invalid argument: 'C:\\x08iserver-ce\\\\ktr\\\\Geo«ì104_Localizacao_imovel_CGDAI_Marco_25.xlsx'\u001b[0m\n\n---\n\n[DESCONHECIDO] \u001b[32m2025-06-19 04:29:53.543\u001b[0m | \u001b[31m\u001b[1mERROR   \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36mrun_pipeline\u001b[0m:\u001b[36m254\u001b[0m - \u001b[31m\u001b[1müí• Pipeline falhou: {'records_processed': 0, 'execution_time': 0, 'errors': 1, 'status': 'failed', 'error': \"[Errno 22] Invalid argument: 'C:\\\\x08iserver-ce\\\\\\\\ktr\\\\\\\\Geo«ì104_Localizacao_imovel_CGDAI_Marco_25.xlsx'\", 'total_execution_time': 0.01123, 'end_time': '2025-06-19T04:29:53.543204'}\u001b[0m"
    },
    {
        "id": "6f58bfe1-824a-4fe3-a909-2fc0f3cbecc7",
        "name": "documento_mgc",
        "status": "Pronto",
        "created_at": "2025-06-19T04:30:42.052369",
        "updated_at": "2025-06-19T04:30:49.487459",
        "project_path": "C:\\ktr_migrator\\ktr_platform\\flows\\6f58bfe1-824a-4fe3-a909-2fc0f3cbecc7",
        "last_run_at": "2025-06-19T04:30:49.487459",
        "execution_status": "Falha",
        "execution_logs": [
            "[2025-06-19T04:30:48.452079] üöÄ Iniciando execu√ß√£o do fluxo...",
            "[2025-06-19T04:30:48.460937] üìÅ Executando: documento_mgc_pipeline.py",
            "[2025-06-19T04:30:49.399162] [ERRO] \u001b[32m2025-06-19 04:30:49.398\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36m__main__\u001b[0m:\u001b[36msetup_logging\u001b[0m:\u001b[36m54\u001b[0m - \u001b[1müöÄ Iniciando pipeline: documento_mgc\u001b[0m",
            "[2025-06-19T04:30:49.433006] [ERRO] Traceback (most recent call last):",
            "[2025-06-19T04:30:49.436527] [ERRO] File \"C:\\ktr_migrator\\ktr_platform\\flows\\6f58bfe1-824a-4fe3-a909-2fc0f3cbecc7\\src\\pipelines\\documento_mgc_pipeline.py\", line 264, in <module>",
            "[2025-06-19T04:30:49.437529] [ERRO] pipeline = DocumentoMgcPipeline(config)",
            "[2025-06-19T04:30:49.439531] [ERRO] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
            "[2025-06-19T04:30:49.440531] [ERRO] File \"C:\\ktr_migrator\\ktr_platform\\flows\\6f58bfe1-824a-4fe3-a909-2fc0f3cbecc7\\src\\pipelines\\documento_mgc_pipeline.py\", line 39, in __init__",
            "[2025-06-19T04:30:49.441530] [ERRO] self.setup_connections()",
            "[2025-06-19T04:30:49.442533] [ERRO] File \"C:\\ktr_migrator\\ktr_platform\\flows\\6f58bfe1-824a-4fe3-a909-2fc0f3cbecc7\\src\\pipelines\\documento_mgc_pipeline.py\", line 60, in setup_connections",
            "[2025-06-19T04:30:49.443532] [ERRO] self.connections[\"DAAS\"] = create_engine(daas_url)",
            "[2025-06-19T04:30:49.445034] [ERRO] ^^^^^^^^^^^^^^^^^^^^^^^",
            "[2025-06-19T04:30:49.446038] [ERRO] File \"<string>\", line 2, in create_engine",
            "[2025-06-19T04:30:49.447047] [ERRO] File \"C:\\Users\\Mota\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sqlalchemy\\util\\deprecations.py\", line 281, in warned",
            "[2025-06-19T04:30:49.449043] [ERRO] return fn(*args, **kwargs)  # type: ignore[no-any-return]",
            "[2025-06-19T04:30:49.449043] [ERRO] ^^^^^^^^^^^^^^^^^^^",
            "[2025-06-19T04:30:49.450049] [ERRO] File \"C:\\Users\\Mota\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 552, in create_engine",
            "[2025-06-19T04:30:49.452664] [ERRO] entrypoint = u._get_entrypoint()",
            "[2025-06-19T04:30:49.453562] [ERRO] ^^^^^^^^^^^^^^^^^^^",
            "[2025-06-19T04:30:49.456259] [ERRO] File \"C:\\Users\\Mota\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sqlalchemy\\engine\\url.py\", line 754, in _get_entrypoint",
            "[2025-06-19T04:30:49.458171] [ERRO] cls = registry.load(name)",
            "[2025-06-19T04:30:49.459164] [ERRO] ^^^^^^^^^^^^^^^^^^^",
            "[2025-06-19T04:30:49.460166] [ERRO] File \"C:\\Users\\Mota\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 374, in load",
            "[2025-06-19T04:30:49.461274] [ERRO] raise exc.NoSuchModuleError(",
            "[2025-06-19T04:30:49.463229] [ERRO] sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:generic",
            "[2025-06-19T04:30:49.483768] üí• Erro detectado, interrompendo execu√ß√£o...",
            "[2025-06-19T04:30:49.489372] ‚ùå Execu√ß√£o falhou com c√≥digo None"
        ],
        "execution_start_time": "2025-06-19T04:30:48.385694",
        "execution_end_time": "2025-06-19T04:30:49.487459",
        "execution_duration": 1.101765,
        "error_message": "[DESCONHECIDO] Traceback (most recent call last):\n\n---\n\n[DESCONHECIDO] raise exc.NoSuchModuleError(\n\n---\n\n[DESCONHECIDO] sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:generic"
    }
]